version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks:
      - dbnest
networks:
  dbnest:
